#!/usr/bin/env node
/**
 * Derive CLOB API creds from PRIVATE_KEY and write algo/.env (local only).
 * Usage: PRIVATE_KEY=0x... node scripts/setup-creds.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ClobClient } from "@polymarket/clob-client-v2";
import { createWalletClient, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { polygon } from "viem/chains";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.join(__dirname, "..", ".env");

const pk = process.env.PRIVATE_KEY;
if (!pk || !pk.startsWith("0x") || pk.length < 66) {
  console.error("Set PRIVATE_KEY=0x... in your shell, then re-run.");
  process.exit(1);
}

const account = privateKeyToAccount(/** @type {`0x${string}`} */ (pk));
const walletClient = createWalletClient({
  account,
  chain: polygon,
  transport: http(process.env.POLYGON_RPC || "https://polygon-rpc.com"),
});

const bootstrap = new ClobClient({
  host: "https://clob.polymarket.com",
  chain: 137,
  signer: walletClient,
});

const creds = await bootstrap.createOrDeriveApiKey();
const funder = process.env.FUNDER_ADDRESS || "";
const sigType = process.env.SIGNATURE_TYPE || "1";

const lines = [
  "# Generated by scripts/setup-creds.mjs — do not commit",
  `PRIVATE_KEY=${pk}`,
  `CLOB_API_KEY=${creds.key}`,
  `CLOB_SECRET=${creds.secret}`,
  `CLOB_PASS_PHRASE=${creds.passphrase}`,
  funder ? `FUNDER_ADDRESS=${funder}` : "# FUNDER_ADDRESS=0x...  # uncomment if Polymarket proxy wallet",
  funder ? `SIGNATURE_TYPE=${sigType}` : "# SIGNATURE_TYPE=1",
  "ALGO_LIVE=1",
  "ALGO_LIMIT_PRICE=0.71",
  "ALGO_ORDER_SIZE=1",
  "ALGO_MARKET_SPAN_SEC=300",
  "ALGO_SLUG_PREFIX=btc-updown-5m",
  "",
];

fs.writeFileSync(ENV_PATH, lines.join("\n"), { mode: 0o600 });
console.log(`Wrote ${ENV_PATH} (mode 600). CLOB key: ${creds.key.slice(0, 8)}…`);
console.log("Restart trader: pkill -f run_supervisor.sh; nohup ./run_supervisor.sh &");
